backend:
  name: git-gateway
  repo: Discovery-Data-Lab/blog # Your GitHub repository
  branch: main # Branch to push changes
  base_url: https://ddlgateway.netlify.app/

media_folder: "static/img" # Folder to store uploaded media files
public_folder: "/img" # Path to access media in the public folder

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    media_folder: "static/img/banners"  # Folder where images will be stored
    public_folder: "/img/banners"       # Path to access media in the public folder
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { 
          label: "Publish Date", 
          name: "date", 
          widget: "datetime",
          format: "YYYY-MM-DDTHH:mm:ss.SSSZ",  
          time_format: "HH:mm:ss",  
          date_format: "YYYY-MM-DD",  
          default: "" ,
          required: false
        }
      - { label: "Tags", name: "tags", widget: "list", default: [], required: false }
      - { label: "Categories", name: "categories", widget: "list", default: [], required: false }
      - { label: "Description", name: "description", widget: "text", required: true }  
      - { label: "Banner Image", name: "banner", widget: "image", required: true }
      - { 
          label: "Authors", 
          name: "authors", 
          widget: "list", 
          default: ["Guilherme Oliveira"], 
          field: { label: "Author", name: "author", widget: "string" },
          required: false 
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  - name: "testimonials"
    label: "Members"
    folder: "data/testimonials"
    media_folder: "/static/img/testimonials"  # Where files are stored in repo
    public_folder: "/img/testimonials"       # URL path Hugo will use
    create: true
    slug: "{{slug}}"
    extension: "yaml"
    format: "yaml"
    fields:
      # Required fields
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Position", name: "position", widget: "string", required: true }
      - { label: "Text", name: "text", widget: "text", required: true }
      - { label: "Avatar", name: "avatar", widget: "image", required: true }

      # Optional fields (no 'required: true')
      - { label: "LinkedIn Link", name: "linkedin_link", widget: "string", required: false }
      - { label: "GitHub Link", name: "github_link", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Personal Site Link", name: "personalSite_link", widget: "string", required: false }
      - { label: "Lattes Curriculum", name: "lattes_link", widget: "string", required: false }
      - { label: "Research Gate Link", name: "researchGate_link", widget: "string", required: false }

  - name: "carousel"
    label: "Carousel"
    folder: "data/carousel"
    create: true
    slug: "{{slug}}"
    extension: "yaml"
    format: "yaml"
    fields:
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "href", widget: "string" }

  - name: "features" 
    label: "Features"
    folder: "data/features" 
    create: true
    slug: "{{slug}}"
    extension: "yaml" 
    format: "yaml"
    fields:
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Icon", name: "icon", widget: "string" }
      - { label: "URL", name: "url", widget: "string", default: "" }
      - { label: "Description", name: "description", widget: "text" }
