name: Deploy Hugo Site to FTP Server

on: 
  schedule: # 11 AM UTC => 8 AM BRT (UTC-3)
    - cron: '0 11 * * *'
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.111.3' 

    - name: Build Hugo site
      run: hugo

    - name: Install Rclone
      run: sudo apt-get install -y rclone

    - name: Configure Rclone
      run: |
        rclone config create ftp ftp host "${{ secrets.FTP_SERVER }}" user "${{ secrets.FTP_USER }}" pass "${{ secrets.FTP_PASSW }}"

    - name: Deploy via Rclone
      run: |
        rclone sync ./public_html ftp:/public_html \
          --ignore-existing \
          --fast-list \
          --transfers=8 \
          --checkers=8 \
          --verbose

