name: Deploy Hugo Site to FTP Server

on: 
  schedule: # 11 AM UTC => 8 AM BRT (UTC-3)
    - cron: '0 11 * * *'
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.111.3' 

    - name: Build Hugo site
      run: hugo

    - name: Install lftp
      run: sudo apt-get install lftp -y

    - name: Configure Rclone
      run: |
        rclone config create ftp ftp host "${{ secrets.FTP_SERVER }}" user "${{ secrets.FTP_USER }}" pass "${{ secrets.FTP_PASSW }}"

    - name: Deploy via LFTP
      run: |
        lftp -u "${{ secrets.FTP_USER }},${{ secrets.FTP_PASSW }}" -e "
        set ftp:ssl-allow no;
        set net:timeout 10;
        set net:max-retries 2;
        mirror -R --parallel=8 --delete ./public_html /public_html;
        bye
        " ${{ secrets.FTP_SERVER }}

